function logisticmat = mk_logistic(varargin)
%MK_LOGISTIC Converts a matrix to a sigmoid curve.
%
%   LOGISTICMAT = MK_LOGISTIC(PIXELMAP, RADIUS [,K]) returns a matrix with the
%   size of PIXELMAP. Elements of the PIXELMAP are used as input values of a
%   sigmoid curve with a steepness of K pixels and a midpoint at X0.
%
%   Arguments:
%      PIXELMAP - a matrix generated by MAP_* functions.
%      RADIUS   - midpoint of the sigmoid.
%      K        - steepness of the sigmoid, -1 if empty or not provided.
%
%   Example:
%     imshow(mk_logistic(map_rectangular(200), 50, -.5));
%
%   See also MAP_SYMMETRIC, MAP_RADIAL, MAP_RECTANGULAR.
	pixelmap = parse_arg(varargin, 1, mfilename, 'pixelmap', [], {'numeric'}, {'nonempty', 'real', 'finite', 'nonnan'});
	radius   = parse_arg(varargin, 2, mfilename, 'radius',   [], {'numeric'}, {'scalar', 'real', 'finite', 'nonnan'});
	k        = parse_arg(varargin, 3, mfilename, 'k',        -1, {'numeric'}, {'scalar', 'real', 'nonnan'});

	logisticmat = 1 ./ (1 + exp(-k * (pixelmap - radius)));
end