function shapemat = mk_shape(varargin)
%MK_SHAPE Converts a matrix to a sigmoid curve.
%
%   SHAPEMAT = MK_SHAPE(PIXELMAP, RADIUS [,PXPITCH]) returns a matrix with the
%   size of PIXELMAP. Elements of the PIXELMAP are thresholded at RADIUS pixels.
%   Pixels near the edge are anti-aliased based on PXPITCH.
%
%   Arguments:
%      PIXELMAP - a matrix generated by MAP_* functions.
%      RADIUS   - edge distance from zero point of the matrix.
%      PXPITCH  - pixel pitch for anti-aliasing, 1 if empty or not provided.
%
%   Example:
%     imshow(mk_shape(MAP_RADIAL(200), 50));
%
%   See also MAP_SYMMETRIC, MAP_RADIAL, MAP_RECTANGULAR.
	pixelmap = parse_arg(varargin, 1, mfilename, 'pixelmap', [], {'numeric'}, {'nonempty', 'real', 'finite', 'nonnan'});
	radius   = parse_arg(varargin, 2, mfilename, 'radius',   [], {'numeric'}, {'scalar', 'real', 'finite', 'nonnan'});
	pxpitch  = parse_arg(varargin, 3, mfilename, 'pxpitch',  1,  {'numeric'}, {'scalar', 'real', 'finite', 'nonnan', 'positive'});

	shapemat = max(min((radius - pixelmap) * pxpitch + .5, pxpitch), 0) / pxpitch;
end